<?php

use Nette\Diagnostics\Debugger;

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/config/Configurator.php';


// Configure application
$configurator = new App\Configurator(__DIR__ . '/../temp');

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode($configurator::AUTO);
$configurator->enableDebugger(__DIR__ . '/../log', 'error@clevis.cz');
Debugger::$showLocation = TRUE;

// Enable RobotLoader - this will load all classes automatically
$loader = $configurator->createRobotLoader();
$loader->register();

// Create Dependency Injection container from configuration files
$container = $configurator->createContainer();

$container->application->catchExceptions = Debugger::$productionMode;

return $container;
