CREATE TABLE tokens (
  id INT AUTO_INCREMENT NOT NULL,
  user_id INT NOT NULL,
  created_at DATETIME NOT NULL,
  hash VARCHAR(255) NOT NULL,
  used_at DATETIME NOT NULL,
  INDEX IDX_AA5A118EA76ED395 (user_id),
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE
  tokens
ADD
  CONSTRAINT FK_AA5A118EA76ED395 FOREIGN KEY (user_id) REFERENCES Users (id);
