CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  created_at DATETIME NOT NULL,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE marathons (
  id INT AUTO_INCREMENT NOT NULL,
  venue_id INT NOT NULL,
  created_at DATETIME NOT NULL,
  name VARCHAR(255) NOT NULL,
  held_at DATETIME NOT NULL,
  INDEX IDX_6C02BCD440A73EBA (venue_id),
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE venues (
  id INT AUTO_INCREMENT NOT NULL,
  created_at DATETIME NOT NULL,
  name VARCHAR(255) NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  street VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE
  marathons
ADD
  CONSTRAINT FK_6C02BCD440A73EBA FOREIGN KEY (venue_id) REFERENCES Venues (id);
