ALTER TABLE
  tokens
DROP
  FOREIGN KEY FK_AA5A118EA76ED395;

ALTER TABLE
  tokens
ADD
  CONSTRAINT FK_AA5A118EA76ED395 FOREIGN KEY (user_id) REFERENCES Attendees (id);

DROP
  TABLE users;

CREATE TABLE attendees (
  id INT AUTO_INCREMENT NOT NULL,
  created_at DATETIME NOT NULL,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE attendees_x_marathons (
  marathon_id INT NOT NULL,
  attendee_id INT NOT NULL,
  INDEX IDX_C71DFCB4A9ED4B6A (marathon_id),
  INDEX IDX_C71DFCB4BCFD782A (attendee_id),
  PRIMARY KEY(marathon_id, attendee_id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE
  attendees_x_marathons
ADD
  CONSTRAINT FK_C71DFCB4A9ED4B6A FOREIGN KEY (marathon_id) REFERENCES attendees (id);

ALTER TABLE
  attendees_x_marathons
ADD
  CONSTRAINT FK_C71DFCB4BCFD782A FOREIGN KEY (attendee_id) REFERENCES marathons (id);
